config/routes.rb
Rails.application.routes.draw do
  
  resources :projects, except: :index do
    member do
      get :pledge
    end
  end

  get 'projects/index'

  get 'projects/show'

  get 'projects/new'

  get 'projects/edit'

  get 'projects/:id/delete' => 'projects#delete', :as => :project_delete

  get '/subjects/:subject_id/projects/:id' => 'projects#show', as: 'project_show'

  resources :subjects
  
  get 'subjects/index'

  get 'subjects/show'

  get 'subjects/new'

  get 'subjects/edit'

  get 'subjects/:id/delete' => 'subjects#delete', :as => :subject_delete

  get 'welcome/home'

  get '/signup' => 'users#new'
  post '/users' => 'users#create'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  root to: 'welcome#home'
end

app/models/project.rb
class Project < ActiveRecord::Base
	belongs_to :subject

	validates :title, presence: true
	validates :creator, presence: true
	validates :image, presence: true
	validates :description, length: { maximum: 1000 }

end

app/models/subject.rb
class Subject < ActiveRecord::Base
	has_many :projects

	validates :name, presence: true
	validates :name, length: { minimum: 2 }
end

app/models/user.rb
class User < ActiveRecord::Base

	has_secure_password

	def admin?
		self.role == 'admin'
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
		if session[:user_id]
      @current_user ||= User.find(session[:user_id])
		else
		  return nil
    end
  end

  helper_method :current_user

  def require_admin
    redirect_to '/' unless current_user.admin?
  end

  def require_user
  	redirect_to '/login' unless current_user
  end


end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  
  before_action :require_user, :except => [:index]

  before_action :require_admin, only: [:new, :create, :edit, :update, :destroy]

  def index
    @subject = Subject.find(params[:id])
    @projects = Project.all
  end

  def show
    @project = Project.find(params[:id])
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    if @project.save
      redirect_to(:action => 'index')
    else
      render('new')
    end
  end

  def edit
    @project = Project.find(params[:id])
  end

  def update
    @project = project.find(params[:id])
    if @project.update_attributes(project_params)
      redirect_to(:action => 'show', :id => @project.id)
    else
      render('index')
    end
  end

  def delete
  end

  private
  def project_params
    params.require(:project).permit(:title, :creator, :description, :image, :goal, :total)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
	end

	def create
		user = User.find_by_email(params[:email])
		if user && user.authenticate(params[:password])
			session[:user_id] = user.id
			redirect_to('/')
		else
			redirect_to('/login')
		end
	end

	def destroy
		session[:user_id] = nil
		redirect_to('/')
	end

end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  
  before_action :require_user, :except => [:index]
  
  before_action :require_admin, only: [:new, :create, :edit, :update, :destroy]

  def index
    @subjects = Subject.all
  end

  def show
    @subject = Subject.find(params[:id])
    @projects = @subject.projects
  end

  def new
    @subject = Subject.new
  end

  def create
    @subject = Subject.new(subject_params)
    if @subject.save
      redirect_to(:action => 'index')
    else
      render('new')
    end
  end

  def edit
    @subject = Subject.find(params[:id])
  end

  def update
    @subject = Subject.find(params[:id])
    if @subject.update_attributes(subject_params)
      redirect_to(:action => 'show', :id => @subject.id)
    else
      render('index')
    end
  end

  def delete
    @subject = Subject.find(params[:id])
  end

  def destroy
    subject = Subject.find(params[:id]).destroy
    redirect_to(:action => 'index')
  end

  private
  def subject_params
    params.require(:subject).permit(:name)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def new
		@user = User.new
	end

	def create
      @user = User.new(user_params)
    	if @user.save
    	  session[:user_id] = @user.id
    	  redirect_to('/')
        else
          redirect_to('/signup')
        end
    end
	
	private
	def user_params
		params.require(:user).permit(:name, :email, :password, :password_confirmation)
	end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def home
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Kickstarter</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag    "bootstrap", :media => "all" %>
  <%= stylesheet_link_tag    "style", :media => "all" %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  
  <link rel="fonts" href="fonts/glyphicons-halflings-regular.woff">
</head>
<body>

<%= yield %>

</body>
</html>

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
  <div class=".form-group-lg floating-label-form-group controls">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :creator %><br>
    <%= f.text_field :creator %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.text_field :image %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
  </div>
<% end %>

app/views/projects/delete.html.erb
<h1>Projects#delete</h1>
<p>Find me in app/views/projects/delete.html.erb</p>

app/views/projects/edit.html.erb
<%= render '/shared/header' %> 

<br>
<br>
<br>
<br>

<h1>Edit Project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project, :class => "btn btn-kickstarter btn-sm" %>
<%= link_to 'Back', projects_path, :class => "btn btn-kickstarter btn-sm" %>

<br>
<br>
<br>
<br>

<%= render '/shared/footer' %>

app/views/projects/index.html.erb
<%= render '/shared/header' %>

<p id="notice"><%= notice %></p>

  <% @projects = @projects.to_a %>

    <div class="project">
      <div class="container">
        <% first = @projects.shift %>
        <% if first %>
          <div class="row">
            <div class="col-xs-5">
              <img src="<%= first.image %>" width="100%">
            </div>
            <div class="col-xs-7">
              <h3 class="title"><%= first.title %></h3>
              <p class="author"><%= first.creator %></p>
              <p class="description"><% first.description %></p>
              <div class="progress">
                <% progress = (first.total / first.goal).to_i %>
                <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width: <%= progress %>%">
                  <span class="sr-only"><%= progress %>% Complete (success)</span>
                </div>
              </div>
            </div>

            <div class="col-xs-1">
              <h4><%= progress %>%</h4>
              <h5>funded</h5>
            </div>
            <div class="col-xs-1">
              <h4>$<%= first.total %></h4>
              <h5>pledged</h5>
            </div>
            <div class="col-xs-2">
              <h4><%= distance_of_time_in_words(Time.now, Time.now + 30.days) %></h4>
              <h5>days to go</h5>
            </div>
          </div>
        <% end %>
      </div>
    </div>


    <div class="popular">
      <div class="container">
          <div class="row">
          <% @projects[0..2].each do |project| %>
            <% next unless project %>
            <div class="col-sm-4">
              <div class="thumbnail">
                <img src="<%= project.image %>">
                <div class="caption">
                  <h3 class="title"><%= project.title %></h3>
                  <p class="author"><%= project.creator %></p>
                  <p class="description"><% project.description %></p>

                  <div class="progress">
                  <% progress = (first.total / first.goal).to_i %>
                    <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width: <%= progress %>%">
                      <span class="sr-only"><%= progress %>% Complete (success)</span>
                    </div>
                  </div>

                  <div class="row">
                    <div class="col-xs-3">
                      <h4><%= progress %>%</h4>
                      <h5>funded</h5>
                    </div>
                    <div class="col-xs-3">
                      <h4>$<%= project.total %></h4>
                      <h5>pledged</h5>
                    </div>
                    <div class="col-xs-3">
                      <h4><%= distance_of_time_in_words(Time.now, Time.now + 30.days) %></h4>
                      <h5>days to go</h5>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          <% end %>
          </div>
      </div>
    </div>
    <div class="promo">
      <div class="container">
        <div class="row">
          <div class="col-md-4">
            <h2>Success</h2>
          </div>
          <div class="col-md-4">
            <h2>Community</h2>
          </div>
          <div class="col-md-4">
            <h2>Start</h2>
          </div>
        </div>
      </div>
    </div>
           

<%= render '/shared/footer' %>

app/views/projects/new.html.erb
<%= render '/shared/header' %> 

<br>
<br>
<br>
<br>

<h1>New Project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path, :class => "btn btn-kickstarter btn-sm" %>

<br>
<br>
<br>
<br>

<%= render '/shared/footer' %> 

app/views/projects/show.html.erb
<%= render '/shared/header' %>

<p id="notice"><%= notice %></p>

    <div class="wrap">
      <div class="project-content">
        <div class="container">
          <h1 class="title"><%= @project.title %></h1>
          <p class="author"><%= @project.creator %></p>
          <div class="project-nav">
            <ul>
              <li class="active">Home</li>
              <li>Comments <span class="label label-default"></span></li>
          </div>
          <div class="project-body">
            <div class="row">
              <div class="col-md-8">
                <img class="img-responsive" src=<%=@project.image %>>
                <p class="subheading"></p>
                <h1> <%= @project.title %> </h1>
                <p><%= @project.description %></p>
              </div>
              <div class="col-md-4">
                <div class="stats">
                  <h1><%= number_to_currency(@project.total) %></h1>
                  <h5>pledged of <h5>
                  <h1> <%= number_to_currency(@project.goal) %></h1>
                  <h5>goal<h5>
                  <h1>4</h1>
                  <h5>days to go</h5>
            </div>
          </div>
      </div>
    </div>


<%= render '/shared/footer' %>

app/views/shared/_footer.html.erb
<!-- Footer -->

<div class="footer">
  <div class="container">
      <div class="links row">
          <div class="col-sm-3">
            <h5>About us</h5>
            <ul>
              <li>What is Kickstarter?</li>
              <li>2013 highlights</li>
              <li>Who we are</li>
              <li>Jobs</li>
              <li>Press</li>
              <li>Stats</li>
              <li>Projects we love</li>
            </ul>
          </div>
          <div class="col-sm-5">
            <h5>Discover</h5>
            <div class="row">
              <div class="col-xs-6">
                <ul>
                  <li>Art</li>
                  <li>Comics</li>
                  <li>Crafts</li>
                  <li>Dance</li>
                  <li>Design</li>
                  <li>Fashion</li>
                  <li>Film &amp; Video</li>
                  <li>Food</li>
                </ul>
              </div>
              <div class="col-xs-6">
                <ul>
                  <li>Games</li>
                  <li>Journalism</li>
                  <li>Music</li>
                  <li>Photography</li>
                  <li>Publishing</li>
                  <li>Technology</li>
                  <li>Theater</li>
                </ul>
              </div>
            </div>
          </div>
          <div class="col-sm-3">
            <h5>Hello</h5>
            <ul>
              <li>Twitter</li>
              <li>Facebook</li>
              <li>Tumblr</li>
              <li>Instagram</li>
              <li>Vine</li>
            </ul>
          </div>
    </div>
        <div class="bottom row">
          <div class="col-md-2">
            <%= image_tag "logo-grey.png", size: "161x20" %>
          </div>
          <div class="pull-right">
            <p>&copy; 2015 Kickstarter, Inc</p>
          </div>
        </div>
  </div>
</div>
</body>
</html>
  

app/views/shared/_header.html.erb
<!-- Header -->

<html>
  <head>
    <link href="css/bootstrap.css" rel='stylesheet'>
    <link href="css/style.css" rel='stylesheet'>
  </head>
  <body>
    <div class="header">
      <div class="container">
        <div class="col-md-2 logo-main">
          <%= link_to image_tag("logo.png", size: "161x20"), root_path, :class => "logo-none"  %>
        </div>
        <div class="col-md-3 byline">
          <ul class="primary">
            <li>Discover</li>
            <li>Start</li>
          </ul>
        </div>
        <div class="user-menu">
        </div>
      </div>
    </div>

app/views/subjects/_form.html.erb
<%= form_for(@subject) do |f| %>
  <% if @subject.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@subject.errors.count, "error") %> prohibited this subject from being saved:</h2>

      <ul>
      <% @subject.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="field">
  <div class=".form-group-lg floating-label-form-group controls">
    <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
    </div>
  <div class="actions">
    <%= f.submit%>
  </div>
</div>
</div>
<% end %>

app/views/subjects/_form_delete.html.erb
<%= form_for(@subject, url: subject_path(:id => @subject.id), html: { :method => :delete}) do |f| %>
  <% if @subject.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@subject.errors.count, "error") %> prohibited this subject from being saved:</h2>

      <ul>
      <% @subject.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="field">
  <div class=".form-group-lg floating-label-form-group controls">
    <div class="field">
    <%= f.label :name, 'Subject name:' %><br>
    <%= @subject.name %>
    </div>
  <div class="actions">
    <%= f.submit "Delete Subject" %>
  </div>
</div>
</div>
<% end %>

app/views/subjects/delete.html.erb
<%= render '/shared/header' %> 

<br>
<br>
<br>
<br>

<h1>Delete Project</h1>

<%= render 'form_delete' %>

<%= link_to 'Back', subject_path, :class => "btn btn-kickstarter btn-sm" %>

<br>
<br>
<br>
<br>

<%= render '/shared/footer' %>

app/views/subjects/edit.html.erb
<%= render '/shared/header' %> 

<br>
<br>
<br>
<br>

<h1>Edit Subject</h1>

<%= render 'form' %>

<%= link_to 'Show', @subject, :class => "btn btn-kickstarter btn-sm" %>
<%= link_to 'Back', subjects_path, :class => "btn btn-kickstarter btn-sm" %>

<br>
<br>
<br>
<br>

<%= render '/shared/footer' %> 

app/views/subjects/index.html.erb
<%= render '/shared/header' %>

<p id="notice"><%= notice %></p>

    <div class="subjects">
      <div class="container">
        <h1>Explore an innovative creative universe</h1>
        <p>15 diverse categories. Thousands of amazing projects.</p>

        <div class="row">
          <% @subjects.in_groups_of(5).each do |subject_group| %>
            <div class="row">
              <div class="col-md-1"></div>
              <% subject_group.each do |subject| %>
                <% next if subject.nil? %>
                <div class="col-md-2">
                  <%= link_to(subject, {class: "thumbnail"}) do %>
                    <h3><%= subject.name %></h3>
                    <% if current_user && current_user.admin? %>
                      <td><%= link_to 'Show', subject %></td>
                      <td><%= link_to 'Edit', edit_subject_path(subject) %></td>
                      <td><%= link_to 'Destroy', subject, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                    <% end %>
                  <% end %>
                </div>
              <% end %>
              <div class="col-md-1"></div>
            </div>
          <% end %>
        </div>
      </div>
    </div>

    <div class="project">
      <div class="container">
        <div class="row">
          <div class="col-xs-5">
            <img src="http://bit.ly/1A94h5v" width="100%">
          </div>
          <div class="col-xs-7">
            <h3 class="title">Title goes here</h3>
            <p class="author">by Author Here</p>
            <p class="description">Description goes here</p>
            <div class="progress">
              <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width: 40%">
                <span class="sr-only">40% Complete (success)</span>
              </div>
            </div>
            <div class="project-status">
              <div class="status-item">
                <h4>60%</h4>
                <h5>funded</h5>
              </div>
              <div class="status-item">
                <h4>$18,246</h4>
                <h5>pledged</h5>
              </div>
              <div class="status-item">
                <h4>187</h4>
                <h5>backers</h5>
              </div>
              <div class="status-item">
                <h4>11</h4>
                <h5>days to go</h5>
              </div>
            </div>
          </div>

        </div>
      </div>
    </div>



<%= render '/shared/footer' %>

app/views/subjects/new.html.erb
<%= render '/shared/header' %> 

<br>
<br>
<br>
<br>

<h1>New Subject</h1>

<%= render 'form' %>

<%= link_to 'Back', subjects_path, :class => "btn btn-kickstarter" %>

<br>
<br>
<br>
<br>

<%= render '/shared/footer' %> 

app/views/subjects/show.html.erb
<%= render '/shared/header' %> 


<h1><%= @subject.name %></h1>
  <% @projects = @projects.to_a %>
  <% first = @projects.shift %>

    <% if first %>
    <div class="project">
      <div class="container">
        <div class="row">
          <div class="col-xs-5">
            <%= link_to project_show_path(@subject, first) do %> 
            <img src="<%= first.image %>" width="100%">
            <% end %>
          </div>
          <div class="col-xs-7">
            <h3 class="title"><%= first.title %></h3>
            <p class="author"><%= first.creator %></p>
            <p class="description"><%= first.description %></p>
            <div class="progress">
              <% progress = (first.total / first.goal).to_i %>
              <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="<%= progress %>" aria-valuemin="0" aria-valuemax="100" style="width: 40%">
                <span class="sr-only"><%= progress %>% Complete (success)</span>
              </div>
            </div>                
          </div>

          <div class="col-xs-1">
            <h4><%= progress %>%</h4>
            <h5>funded</h5>
          </div>
          <div class="col-xs-1">
            <h4>$<%= first.total %></h4>
            <h5>pledged</h5>
          </div>
          <div class="col-xs-2">
            <h4><%= distance_of_time_in_words(Time.now, Time.now + 30.days) %></h4>
            <h5>days to go</h5>
          </div>
        </div>
      </div>
    </div>
    <% end %>
    <% @projects.in_groups_of(3).each do |projects_group| %>
      <div class="container">
        <div class="row">
          <% projects_group.each do |project| %>
            <% next unless project %>
            <div class="col-sm-4">
              <div class="thumbnail">
                <img src="<%= project.image %>">
                <div class="caption">
                  <h3 class="title"><%= project.title %></h3>
                  <p class="author"><%= project.creator %></p>
                  <p class="description"><%= project.description %></p>
                  
                  <div class="progress">
                    <% progress = (project.total / project.goal).to_i %>
                    <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width: 80%">
                      <span class="sr-only"><%= project %>% Complete (success)</span>
                    </div>
                  </div> 

                  <div class="row">
                    <div class="col-xs-3">
                      <h4><%= progress %>%</h4>
                      <h5>funded</h5>
                    </div>
                    <div class="col-xs-3">
                      <h4>$<%= project.total %></h4>
                      <h5>pledged</h5>
                    </div>
                    <div class="col-xs-3">
                      <h4><%= distance_of_time_in_words(Time.now, Time.now + 30.days) %></h4>
                      <h5>days to go</h5>
                    </div>                
                  </div>
                </div>
              </div>
            </div>
            <% end %>
      </div>
    </div>
    <% end %>

    <div class="promo">
      <div class="container">
        <div class="row">
          <div class="col-md-4">
            <h2>Success</h2>
          </div>
          <div class="col-md-4">
            <h2>Community</h2>
          </div>
          <div class="col-md-4">
            <h2>Start</h2>
          </div>
        </div>
      </div>
    </div>



<%= render '/shared/footer' %> 

app/views/users/new.html.erb
<%= render '/shared/header' %>

<br>
<br>
<div class="main">
  <div class="container">
    <div class="row">
      <div class="col-md-5 col-md-offset-3">
        <div class="center-text">
          <h1>Sign Up!</h1>
        </div>
		<%= form_for :user, url: '/users' do |f| %>
          <div class="form-group">
            <%= f.label :name %>
		    <%= f.text_field :name, class: 'form-control', placeholder: 'Enter your name' %> 
		  </div>
		  <div class="form-group">
		    <%= f.label :email %>
		    <%= f.text_field :email, class: 'form-control', placeholder: 'Enter email' %>
		  </div>
		  <div class="form-group">
            <%= f.label :password %>
		    <%= f.password_field :password, class: 'form-control', placeholder: 'Enter password' %> 
		  </div>
		  <div class="form-group">
		    <%= f.label :password_confirmation %>
		    <%= f.password_field :password_confirmation, class: 'form-control', placeholder: 'Enter password confirmation' %> 
		  </div>
		  <%= f.submit %> 

		<% end %>
      </div>
    </div>
  </div>
</div>
<br>
<br>

<%= render '/shared/footer' %>